  version: "3.9"
  services:
    postgres:
     image: postgres:12-alpine
     environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: postgres
    api:
      build: 
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      env
      