  version: "3.9"
  services:
    db:
      image: postgres:12-alpine
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
      ports:
        - 5432:5432
      volumes:
        - postgres_data:/var/lib/postgresql/data/
    web:
      build: .
      command: python manage.py runserver