apiVersion: 1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::181994008210:user/github-ci
      username: admin
      groups:
        - system:masters