name: Deploy to Production

on:
  push:
    branches: [ "main" ]

jobs:

  test:
    name: Build and Deploy to Amazon ECR
    runs-on: ubuntu-latest
    steps:
    - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1